### PR TITLE
how about to add word of "framework" ?

### PR DESCRIPTION
**Pull request by KazuCocoa**
Just suggestion.

How about to add word of "Framework" for unit/integration/e2e tests ?
Because this list doesn't mention test level.

### CODE REVIEW

**Comment by hotchemi** [comment]
Thanks!
I think "framework" and "library" are mixed in this list...for example, junit is a framework but burst is just a libary, how do u think about of it?

**Comment by KazuCocoa** [comment]
u'r right.
I suppose that ...
- Frameworks are top level tools to run tests
- Libraries help frameworks

So, how about to make nest only for unit/integration/e2e test categories ?

```
# Unit Test framework
- JUnit

## Libraries
- Burst
```

But, I'm concerned that nested list looks a bit complicated ...

**Comment by hotchemi** [comment]
Your suggestion is really nice! I'll do that after merged. Thx :)

**Comment by KazuCocoa** [comment]
:dance:

—
Mailbox から送信

**Pull request merged**
